allowed-duplicate-crates = [
	"hashbrown",
	"json5",
	"rand",
	"rand_chacha",
	"rand_core",
	"redox_syscall",
	"toml",
	"toml_datetime",
	"windows-core",
	"windows-link",
	"windows-result",
	"windows-strings",
	"winnow",
]
