services:
  ssh-server:
    image: lscr.io/linuxserver/openssh-server@sha256:f8e221e7dce7979a0110d13451e0be8d539b86d818c0fb7c71c5271ddf32f3bf
    container_name: ssh_test_server
    ports:
      - "2222:2222"
    environment:
      - USER_NAME=testuser
      - USER_PASSWORD=password123
      - PASSWORD_ACCESS=true
