services:
  ssh-server:
    image: lscr.io/linuxserver/openssh-server@sha256:57c13941ef385d735cca18ee969eeba18e42ab95480c97af2182505aacdfe307
    container_name: ssh_test_server
    ports:
      - "2222:2222"
    environment:
      - USER_NAME=testuser
      - USER_PASSWORD=password123
      - PASSWORD_ACCESS=true
