[tools]
rust = { version = "1.98.0", profile = "default" }
"aqua:EmbarkStudios/cargo-deny" = "0.20.2"
"github:xd009642/tarpaulin" = "0.37.2"
usage = "6.5.0"
hk = "1.56.1"
actionlint = "1.7.12"
# used in actionlint
shellcheck = "0.11.0"
ghalint = "1.5.6"
pinact = "4.1.1"
zizmor = "1.29.0"
# required for pipx backend
uv = "0.12.7"
yamllint = "1.38.0"
yamlfmt = "0.21.0"
typos = "1.50.0"
release-plz = "0.3.159"
cargo-dist = "0.32.0"
bun = "1.4.0"
node = "26.8.1"
oxlint = "1.72.0"
oxfmt = "0.65.0"
pitchfork = "2.23.0"
tombi = "1.2.10"
"npm:ajv-cli" = "5.0.0"
wrangler = "4.127.0"
jq = "1.8.2"
yq = "4.53.6"

[settings]
experimental = true
lockfile_platforms = [
	"linux-arm64",
	"linux-arm64-musl",
	"linux-x64",
	"linux-x64-musl",
	"macos-arm64",
	"macos-x64",
]

[env]
"_".path = ["target/debug"]

[task_config]
includes = ["tasks.toml", "tasks/"]

[task_templates."ssh-tests"]
depends = ["test:ssh-server"]

[task_templates."ssh-tests".env]
BIWA_TEST_SSH_PORT = { default = "{{ exec(command='pitchfork status ssh-server --json | jq --exit-status --raw-output \".port[0]\"') }}" }
BIWA_TEST_SSH_CAPABLE_PORT = { default = "{{ exec(command='pitchfork status ssh-server --json | jq --exit-status --raw-output \".port[1]\"') }}" }

[deps.bun_docs]
auto = true
sources = ["docs/bun.lock", "docs/package.json"]
outputs = ["docs/node_modules"]
run = "cd docs && bun install --frozen-lockfile"
